### PR TITLE
Show compiler flags for all CoreCLR builds

### PR DESCRIPTION
**Pull request by saper**
As a baseline build, having a full commandline
to trouble shoot building issues can be handy.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1: 
I think this should be done with Linux, Mac and Win debug configs as well.
@mmitche

**Comment by saper** [comment]
Debug only? release as well?

**Comment by mmitche** [comment]
@saper Do we want this for windows too?

**Comment by saper** [comment]
`msbuild` produces strange output sometimes to me but it can't hurt.

**Comment by mmitche** [comment]
I'll make sure it works.  Actually might want to add an option to the build.cmd script to get this done.

**Comment by mmitche** [comment]
@saper So that should actually be done as a separate commit, since it won't build anything unless we add the Verbose option to the script.  We can merge the original and do the other one as a separate commit.

**Comment by mmitche** [comment]
LGTM otherwise.

**Comment by saper** [comment]
Ah, right. Should be trivial to do. But no Visual Studio here, sorry.

**Comment by mmitche** [comment]
@saper Looking good there.  Thanks for your contribution.

I realized the Windows are spitting the command line in most instances as well as to a file.

**Pull request merged**
