### PR TITLE
Add async-main features

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by TyOverby** [comment]
@mmitche @dotnet/roslyn-infrastructure : review please!

Also, do I need to mess around with the dotnet-ci-internal repo?

**Comment by jasonmalinowski** [comment]
@TyOverby If you want internal integration tests. I wouldn't be worried here.

**Comment by TyOverby** [comment]
@jasonmalinowski : great!

Do you have merge permissions?

**Comment by mmitche** [comment]
@TyOverby don't think so.

**Pull request merged**
