### PR TITLE
Add label for arm64 windows machines

### PR DESCRIPTION
**Pull request by jashook**

### CODE REVIEW

**Comment by mmitche** [comment]
@jashook Is this for build machines or test machines?

**Comment by jashook** [comment]
Test

**Comment by jashook** [comment]
It is a pre-req to drop the arm64 internal ci

**Comment by jashook** [comment]
Safe to ignore failures?

**Comment by mmitche** [comment]
@jashook Yeah.  The "CI Tests" legs only work if you pushed to upstream (security)

**Comment by jashook** [comment]
That doesnt make sense to me but I can bug you about it later.

**Comment by jashook** [comment]
Thanks

**Pull request merged**
