### PR TITLE
Ability to pass SCM credentials through

### PR DESCRIPTION
**Pull request by jaredpar**
Roslyn needs this ability as we utilize private repos in our Jenkins setup.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @mmitche 

This was one gap I saw when porting the roslyn-internal groovy setup to dotnet-ci.

**Comment by mmitche** [comment]
@jaredpar That is actually in InternalUtilities.addPrivateScm

**Comment by jaredpar** [comment]
@mmitche don't see that.  Where can I see the groovy script to use as a reference?

**Comment by jaredpar** [comment]
@mmitche hmm,

**Pull request closed without merging**
