### PR TITLE
Add new ChakraCore branches

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by mmitche** [comment]
@dilijev Can we test these out on dotnet-ci2?  Should work just fine (just change the server to dotnet-ci2)

**Comment by dilijev** [comment]
@mmitche ok!

**Comment by mmitche** [comment]
I think you guys put the hooks in, so this is good to go.

**Comment by dilijev** [comment]
Looks like all branches have some set of default checks that work even if we don't do this update. How does splitting this between the two servers affect those?

**Pull request merged**
