### PR TITLE
Add Microsoft/TypeScript

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Also fixed some spelling / missing terms in comments

### CODE REVIEW

**Comment by mmitche** [comment]
What machine types are you guys going to need?  I might put you on the secondary server

**Comment by RyanCavanaugh** [comment]
Only Linux

**Comment by mmitche** [comment]
perfect, can you change the dotnet-ci in your line to dotnet-ci2?

**Comment by RyanCavanaugh** [comment]
Done

**Comment by RyanCavanaugh** [comment]
@mmitche anything else blocking this?

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
