### PR TITLE
Disable Jenkins builds for aspnet/SignalR

### PR DESCRIPTION
**Pull request by anurse**
We're getting enough coverage from AzDO now and are ready to shut off the Jenkins builds. It looks like this is the way to do that :).

cc @pranavkm @mmitche

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by BrennanConroy** [comment]
Shouldn't we keep the release/2.1 build since AzDo doesn't run those?

**Comment by mmitche** [comment]
@pranavkm Please confrim 2.1 is run out of AzDO.

**Comment by pranavkm** [comment]
>  Please confrim 2.1 is run out of AzDO.

@natemcmaster \ @ryanbrandenburg would know this best.

**Comment by ryanbrandenburg** [comment]
2.1 is not run on AzDO, that can be changed [from here](https://dnceng.visualstudio.com/public/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=26&view=Tab_Triggers) if it works.

**Comment by natemcmaster** [comment]
There is no reason you can't get PR validation on AzDO in release/2.1 though. We've set it up for a few repos already, like aspnet/Extensions.

**Comment by anurse** [comment]
I'll restore the 2.1 build. I'd like to get 2.1 running in AzDO, but that's more work than I'm ready for now. Filed https://github.com/aspnet/SignalR/issues/3239 to track the (very minimal) work to get release/2.1 building in AzDO.

**Pull request merged**
