### PR TITLE
Add corefx release/1.0.1 branch

### PR DESCRIPTION
**Pull request by ericstj**
/cc @weshaggard @mmitche

### CODE REVIEW

**Comment by mmitche** [comment]
@ericstj LGTM Do we still need rc2?

**Comment by ericstj** [comment]
> Do we still need rc2?

We might, not sure what the support lifecycle is for that pre-release, @leecow?

**Comment by leecow** [comment]
@ericstj - Yes, RC2 is supported until September. https://www.microsoft.com/net/support

**Comment by ericstj** [comment]
Ok, @mmitche good to merge as is then.  Could you do that?

**Pull request merged**
