### PR TITLE
Add CI Coverage for WCF 1.1.0

### PR DESCRIPTION
**Pull request by hongdai**
* Need to add CI coverage for the new branch WCF 1.1.0

### CODE REVIEW

**Comment by hongdai** [comment]
Ready for review, but please do NOT merge until instructed. There are several other things need to happen in order.

**Comment by mmitche** [comment]
lgtm

**Comment by iamjasonp** [comment]
LGTM. @hongdai, prior to merge, please modify the title of the issue as it gets populated as the body of the merge commit

**Comment by roncain** [comment]
LGTM.
I believe all steps have been completed for this to be merged.

**Pull request merged**
