### PR TITLE
Add CI dev branches for ChakraCore.

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/dotnet/dotnet-ci/278)

### CODE REVIEW

**Comment by dilijev** [comment]
FYI @digitalinfinity @obastemur

**Comment by digitalinfinity** [comment]
👍

**Comment by mmitche** [comment]
The only thing you might want to make sure about is that the CI branches don't have a bunch of jobs that are going to run things nightly, since the results aren't useful most of the time.  You could disable the triggers until they are needed.

**Comment by dilijev** [comment]
@mmitche I was thinking about that possibly being a problem. I think that will mostly be resolved by dev workflow. For the moment, I don't think anything will run on these branches because the daily tasks are scheduled based on specific branch names. During development the daily triggers could be turned on if that was necessary, and then turned off and restricted to just the actual target branches.

**Comment by mmitche** [comment]
Sounds fine to me, merge away

**Comment by dilijev** [comment]
Oh, I see that for other branches, the daily tasks are still created, just targeted at a different branch. That's by design... I think I could add an exception for branches ending in `-ci` to remove those daily triggers.

Anyway at the moment these branches don't exist (and we may choose not to have these branches exist unless there's ongoing development). What will happen in this case?

**Comment by dilijev** [comment]
@mmitche I don't believe I have the authority to merge this PR

**Comment by obastemur** [comment]
:100:

**Comment by dilijev** [comment]
@mmitche thanks! I'll keep an eye out for unnecessary daily jobs and update accordingly.

**Pull request merged**
