### PR TITLE
Add dotnet-apiport/service branch for build

### PR DESCRIPTION
**Pull request by conniey**
Adding dotnet-apiport/service branch for dotnet-bot to build because we are doing new dev work on that branch.

### CODE REVIEW

**Comment by conniey** [comment]
Hey @mmitche 
I am trying to make sense of the CI tests failures. Am I missing some generation step?
```
[Pipeline] echo
This is a GitHub PR test
[Pipeline] error
[Pipeline] End of Pipeline
```

**Comment by mmitche** [comment]
Ignore

**Comment by conniey** [comment]
@mmitche Thanks for the quick response! How long does it take before the trigger works for a new branch? (ie. adding `@dotnet-bot test this please` from a PR into our `service` branch)

**Comment by mmitche** [comment]
Should work now

**Pull request merged**
