### PR TITLE
Add Ubuntu 15.10 and RHEL7 to affinity list

### PR DESCRIPTION
**Pull request by ellismg**
We want to get runs on Ubuntu 15.10 and RHEL 7 for CoreFX and CoreCLR, this is in preparation for that.

### CODE REVIEW

**Comment by mmitche** [comment]
@ellismg Nope that is all automatic.

**Comment by ellismg** [comment]
Not clear to me that the failure in CI is my fault.

**Comment by mmitche** [comment]
It's not.

Sent from my Windows Phone
________________________________

**Comment by mmitche** [comment]
@ellismg Not even the same CI server.  That was some random test I was running on the test ci server.

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
