### PR TITLE
Publish artifacts from obj/

### PR DESCRIPTION
**Pull request by saper**
In order to troubleshoot issues
related to BclRewriter and the
generation of final mscorlib.dll
assembly it would be great
to have a version of library
published *before* BclRewriter
process as well as its logs.

Sample issue:

https://github.com/dotnet/coreclr/issues/1151

### CODE REVIEW

**Comment by saper** [comment]
It would be great to have this enabled also for pull requests, but we currently do not archive any artifacts there (which is probably a good thing due to resources required).

Would there be a possibility to include some conditional logic to publish those artifacts on-demand only? (For example based on some keyword in the scm commit log)

**Comment by mmitche** [comment]
@saper Do you know how big the obj dir is typically?

Unfortunately there doesn't appear to be an easy way to conditionally pull the artifacts in the current plugin.

**Comment by saper** [comment]
````
m> find obj/
obj/
obj/FreeBSD.x64.Debug
obj/FreeBSD.x64.Debug/BclRewriter
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.apiClosure.xml
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.dll
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.implClosure.xml
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.pdb
obj/FreeBSD.x64.Debug/GeneratedAssemblyInfo.cs
obj/FreeBSD.x64.Debug/GeneratedVersion.h
obj/FreeBSD.x64.Debug/moduleName.rsp
obj/FreeBSD.x64.Debug/mscorlib.csproj.FileListAbsolute.txt
obj/FreeBSD.x64.Debug/mscorlib.dll
obj/FreeBSD.x64.Debug/mscorlib.pdb
obj/FreeBSD.x64.Debug/mscorlib.resources
obj/FreeBSD.x64.Debug/NativeVersion.res
m> du -ks obj
20232	obj
````

20 meg

````
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.dll
obj/FreeBSD.x64.Debug/BclRewriter/mscorlib.pdb
````

seem to be the same as their `Product/FreeBSD.x64.Debug` versions, so could be also excluded saving some 8 megabytes

**Comment by mmitche** [comment]
@saper The obj dir for the windows builds is around 3.8 GB...Can we change this so that we simply have a pre-BCLRewriter mscorlib instead of archiving all of obj?

**Comment by saper** [comment]
OMG, I never inteded to publish this! Of course what I need is just pre-BclRewriter library and resources....

**Comment by saper** [comment]
https://github.com/saper/dotnet-ci/commit/799971316f48b21973cd8cb7c54b247a34ae231f should include only the files we need (explicitly)

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by mmitche** [comment]
Looks fine to me.  FYI merging this does automatically bring in the changes. I'll need to pull them in server side.

**Comment by saper** [comment]
Thank you very much. Just checked out the artifacts generated and this is what I need.

**Comment by mmitche** [comment]
Ya sorry it took so long,

**Comment by saper** [comment]
No problem, I didn't have time either :)

**Pull request merged**
