### PR TITLE
Add experimental-classic-projects dotnet/sdk branch

### PR DESCRIPTION
**Pull request by dsplaisted**
@mmitche for review

### CODE REVIEW

**Comment by dsplaisted** [comment]
@dotnet/dnceng Can someone look at why 3 of the legs for this PR are failing?

**Comment by dsplaisted** [comment]
@dotnet-bot test CI Tests (dotnet-ci)

**Comment by dsplaisted** [comment]
@dagood @mmitche How long until these changes take effect?  I'm not seeing CI runs on https://github.com/dotnet/sdk/pull/2427

**Comment by mmitche** [comment]
@dsplaisted Take a few minutes for the generators to run.  I'll poke it when it's ready.

**Pull request merged**
