### PR TITLE
Add CoreFX/CoreCLR RTM branches

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
@mmitche I have created the RTM branches, is it safe to do this now?
/cc @Priya91

**Comment by mmitche** [comment]
@ellismg Do we still need the rc2 branches?

**Comment by ellismg** [comment]
@mmitche We want to keep them around until RTM is done in case we need to service RC2, we'd like Jenkins coverage until then, if that's ok?

**Comment by mmitche** [comment]
OKay sounds good.  Wondering about some of the rolling jobs.  If the rate of change is really low we will be running a bunch of stuff unnecessarily.  I wonder whether the rolling stuff should instead be just checking source control on the rolling interval, and only running if something changes.

**Comment by ellismg** [comment]
> I wonder whether the rolling stuff should instead be just checking source control on the rolling interval, and only running if something changes.

Does Jenkins provide a way to not kick off a job if the SHA of HEAD hasn't changed and there's a successful build at that SHA?

**Comment by mmitche** [comment]
Yeah, "poll scm".  Today we have our timed jobs on cron triggers.  You can set the same cron trigger to a poll scm, which will simply not run if the sha hasn't changed.  Of course, you probably don't want that in all cases, since the sha isn't the only thing that contributes to the builds (nuget, for instance)

**Comment by ellismg** [comment]
> Of course, you probably don't want that in all cases, since the sha isn't the only thing that contributes to the builds (nuget, for instance)

Sure, we'll look into what we can clean up for RC2 and RTM next week.

**Pull request merged**
