### PR TITLE
Cherry-pick 0f589555ba782baab5effd2b05df203edf4a16d6 from master

### PR DESCRIPTION
**Pull request by zamont**
Add CI for release/uwp6.0 branches of coreclr and corefx (#733)

* Add CI for release/uwp6.0 branches of coreclr and corefx

* Add CI for wcf and core-setup release/uwp6.0 branches

* Add ability to run helix test infra for corefx release/uwp6.0

### CODE REVIEW

**Comment by zamont** [comment]
@mmitche @maririos @weshaggard PTAL

**Comment by joshfree** [comment]
Thanks @zamont

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@dotnet-bot this this please

**Comment by zamont** [comment]
@smile21prc is taking a look at this failure

**Comment by karajas** [comment]
@dotnet-bot test this please

**Comment by smile21prc** [comment]
@dotnet-bot test this please

**Comment by karajas** [comment]
As far as I can tell this is a jenkins core issue, documented here https://issues.jenkins-ci.org/browse/JENKINS-40117

**Comment by karajas** [comment]
LGTM.

**Comment by joshfree** [comment]
merging this now as it has passed CI

**Comment by smile21prc** [comment]
The previous CI failures should have been caused by the version upgrading (https://issues.jenkins-ci.org/browse/JENKINS-40117) as it passed after I rebooted ci3 master.

**Pull request merged**
