### PR TITLE
Update windows nano server labels to pick the latest version.

### PR DESCRIPTION
**Pull request by Priya91**
cc @mmitche @joshfree 

In reference to issue dotnet/corefx#7939

### CODE REVIEW

**Comment by mmitche** [comment]
LGTM

**Comment by joshfree** [comment]
should this be "Windows Nano Server 2016" or something with a version so we don't have to change this again in the future when the next version comes out after this one?

**Comment by Priya91** [comment]
@joshfree I removed the version strings from the labels and OS, so this doesn't have to be updated for every build update..

**Comment by joshfree** [comment]
right.  though this feels a bit like the same mistake we made calling Ubuntu 14.04 just "ubuntu" in all the build scripts initially.

**Comment by Priya91** [comment]
@joshfree makes sense, will name the OS as Windows Nano 2016

**Pull request merged**
