### PR TITLE
Add new Ubuntu 16.04 and Ubuntu 16.10 images

### PR DESCRIPTION
**Pull request by mellinoe**
@mmitche

### CODE REVIEW

**Comment by rainersigwald** [comment]
@mellinoe @mmitche Is it possible that some of the 16.04 images are mislabeled? MSBuild is seeing builds fail that seem to be because they're running on 16.10, even though we're requesting 16.04.

Example: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_Ubuntu16.04_CoreCLR_prtest/411/console shows that the machine [ubuntu1604-20170216-f15060](https://ci2.dot.net/computer/ubuntu1604-20170216-f15060/) is running image `ubuntu1604-20170216`, but `lsb_release` says

```
09:34:17 No LSB modules are available.
09:34:17 Distributor ID:	Ubuntu
09:34:17 Description:	Ubuntu Yakkety Yak (development branch)
09:34:17 Release:	16.10
09:34:17 Codename:	yakkety
```

**Comment by mellinoe** [comment]
@mmitche Was the image that you handed off to me actually an Ubuntu 16.10 image? I can take a look at this in a little bit, seems like we might have mixed something up.

**Comment by mmitche** [comment]
@mellinoe AFAIK.  Nope, it just looks like when this config on ci2 got updated the wrong VHD URI was included.  Fixed.

**Comment by rainersigwald** [comment]
Thanks @mmitche. Our builds seem to be reliably passing now: https://ci2.dot.net/job/Microsoft_msbuild/job/master/job/_Ubuntu16.04_CoreCLR_prtest/

**Pull request merged**
